### ISSUE TITLE
item(...).replace is not a function

### ISSUE THREAD

**Issue by kolmpjess** [custom-cards/upcoming-media-card#90]
Hi
I have an issue with the custom component for Emby i am getting the error "item(...).replace is not a function".
Looking further into it, it leads me to this part of upcoming-media-card.js on line 593 which the block of code starts at line 585:

`// Keyword map for replacement, return null if empty so we can hide empty sections
let keywords = /$title|$episode|$genres|$number|$rating|$release|$runtime|$studio|$price|$day|$date|$time|$aired|$album|$artist/g;
let keys = {
$title: item("title") || null,
$episode: item("episode") || null,
$genres: item("genres") || null,
$number: item("number") || null,
$rating: item("rating") || null,
$release: item("release").replace("$date", format_date(item("airdate"), dateform)).replace("$year", format_date(item("airdate"), "yy")).replace(" $time", "  $ti>
$studio: item("studio") || null,
$price: item("price") || null,
$album: item("album") || null,
$artist: item("artist") || null,
$runtime: runtime || null,
$day: day || null,
$time: airdate.toLocaleTimeString([], timeform) || null,
$aired: format_date(item("aired"), dateform) || null
};`

Any suggestions on how to fix this?
When i unquote $release all other parts work fine.

Thanks for your time.

**Comment by mkanet** [comment]
Hi @kolmpjess my apologies.  Thank you for letting me know.  Please try the latest version, 0.5.3; which I _just_ pushed out.  It should fix this.

**Comment by kolmpjess** [comment]
> Hi @kolmpjess my apologies. Thank you for letting me know. Please try the latest version, 0.5.3; which I _just_ pushed out. It should fix this.

Yes this fixed the issue. Thanks for the quick update and have a great weekend!

**Comment by gcorgnet** [comment]
Hi, it seems like this issue is still happening on latest version (0.5.5)
Could you please check? Thanks
